version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"

apache_fallback_resource: "/index.php"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  test:
    - "ptest"

